{{- include "invidious.init-defaults" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
stringData:
  INVIDIOUS_CONFIG: |
    {{- toYaml .Values.config | nindent 4 }}
